server:
  port: 8721

spring:
  application:
    name: sentinel-resttemplate-test
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.6.128:8863

    sentinel:
      transport:
        dashboard: 127.0.0.1:9090
